
import React from 'react';
import { Account, AccountCategory, WellStatus } from './types';

export const COLORS = {
  primary: '#00AEEF',
  darkBg: '#0f172a',
  sidebarBg: '#1e293b',
  cardBg: '#1e293b',
  textHeader: '#00AEEF',
};

const rawAccounts = [
  // 1000 - الأصول (Assets)
  { code: 1110, ar: "الصندوق الرئيسي", en: "Main Cash", cat: AccountCategory.ASSETS },
  { code: 1111, ar: "نثرية موقع الحقل", en: "Field Petty Cash", cat: AccountCategory.ASSETS },
  { code: 1121, ar: "بنك الرافدين - دولار", en: "Rafidain Bank - USD", cat: AccountCategory.ASSETS },
  { code: 1122, ar: "مصرف التجارة العراقي", en: "TBI Bank", cat: AccountCategory.ASSETS },
  { code: 1131, ar: "شركة نفط البصرة (ذمم مدينة)", en: "Basra Oil Co (A/R)", cat: AccountCategory.ASSETS },
  { code: 1171, ar: "مخزون رؤوس حفر (Drill Bits)", en: "Drill Bits Stock", cat: AccountCategory.ASSETS },
  { code: 1172, ar: "مخزون مواسير حفر (Casing)", en: "Casing Stock", cat: AccountCategory.ASSETS },
  { code: 1174, ar: "مخزون طين حفر (Mud Stock)", en: "Drilling Mud Stock", cat: AccountCategory.ASSETS },
  { code: 1179, ar: "مخزون مواد السلامة PPE", en: "PPE Safety Stock", cat: AccountCategory.ASSETS },
  // 5000 - المصروفات (Expenses)
  { code: 5101, ar: "مصاريف تشغيل الآبار", en: "Well Operating Expenses", cat: AccountCategory.EXPENSES },
  { code: 5102, ar: "مصاريف صيانة الحقول", en: "Field Maintenance Expenses", cat: AccountCategory.EXPENSES }
];

export const generateAccounts = (): Account[] => {
  return rawAccounts.map((a, i) => ({
    id: `acc-${a.code}-${i}`,
    code: a.code,
    nameAr: a.ar,
    nameEn: a.en || '',
    displayName: `${a.code} - ${a.ar} / ${a.en || ''}`,
    category: a.cat || AccountCategory.OTHERS,
    balance: 0
  }));
};

export const CHART_OF_ACCOUNTS = generateAccounts();

export const Logo = ({ className = "w-12 h-12" }: { className?: string }) => (
  <div className={`${className} flex items-center justify-center font-tech font-black text-3xl text-[#00AEEF] tracking-tighter select-none`}>
    <svg viewBox="0 0 24 24" fill="currentColor" className="w-8 h-8 mr-2"><path d="M12,15.5A3.5,3.5 0 0,1 8.5,12A3.5,3.5 0 0,1 12,8.5A3.5,3.5 0 0,1 15.5,12A3.5,3.5 0 0,1 12,15.5M19.43,12.97C19.47,12.65 19.5,12.33 19.5,12C19.5,11.67 19.47,11.34 19.43,11L21.54,9.37C21.73,9.22 21.78,8.95 21.66,8.73L19.66,5.27C19.54,5.05 19.27,4.96 19.05,5.05L16.56,6.05C16.04,5.66 15.47,5.32 14.87,5.07L14.5,2.42C14.46,2.18 14.25,2 14,2H10C9.75,2 9.54,2.18 9.5,2.42L9.13,5.07C8.53,5.32 7.96,5.66 7.44,6.05L4.95,5.05C4.73,4.96 4.46,5.05 4.34,5.27L2.34,8.73C2.21,8.95 2.27,9.22 2.46,9.37L4.57,11C4.53,11.34 4.5,11.67 4.5,12C4.5,12.33 4.53,12.65 4.57,12.97L2.46,14.63C2.27,14.78 2.21,15.05 2.34,15.27L4.34,18.73C4.46,18.95 4.73,19.03 4.95,18.95L7.44,17.94C7.96,18.34 8.53,18.68 9.13,18.93L9.5,21.58C9.54,21.82 9.75,22 10,22H14C14.25,22 14.46,21.82 14.5,21.58L14.87,18.93C15.47,18.68 16.04,18.34 16.56,17.94L19.05,18.95C19.27,19.03 19.54,18.95 19.66,18.73L21.66,15.27C21.78,15.05 21.73,14.78 21.54,14.63L19.43,12.97Z" /></svg>
    FX
  </div>
);

export const TRANSLATIONS = {
  ar: {
    dashboard: "لوحة التحكم",
    journal: "دفتر اليومية",
    wells: "إدارة الآبار",
    partners: "إدارة الشركاء",
    inventory: "إدارة المخازن",
    reports: "مركز التقارير والرقابة",
    chart: "الدليل المحاسبي النفطي",
    audit: "سجلات التعديلات والحذف",
    users: "إدارة المستخدمين",
    settings: "إعدادات النظام",
    logout: "تسجيل الخروج",
    loginTitle: "نظام FineX للطاقة",
    loginSub: "يرجى إدخال بيانات الاعتماد للوصول للنظام",
    adminSetupTitle: "تأسيس مدير النظام",
    adminSetupSub: "الرجاء إدخال بيانات المدير الأول لتأسيس النظام",
    adminLogin: "مدير النظام - Admin Login",
    phone: "رقم الهاتف",
    password: "كلمة المرور",
    loginBtn: "دخول للنظام",
    setupBtn: "تأسيس الحساب والمتابعة",
    invalidLogin: "رقم الهاتف أو كلمة المرور غير صحيحة",
    userBlocked: "عذراً، تم حظر وصولك للنظام من قبل الإدارة",
    fullName: "الاسم الثلاثي الكامل",
    jobTitle: "العنوان الوظيفي",
    addUser: "إضافة مستخدم جديد +",
    permissions: "صلاحيات الوصول",
    block: "حظر",
    unblock: "إلغاء الحظر",
    active: "نشط",
    blocked: "محظور",
    performedBy: "بواسطة",
    systemAlert: "تنبيه النظام",
    totalAssets: "إجمالي الأصول",
    totalLiabilities: "إجمالي الالتزامات",
    actualProduction: "إجمالي الإنتاج الفعلي",
    wtiPrice: "سعر خام WTI اللحظي",
    realTime: "مباشر",
    newEntry: "إضافة قيد جديد",
    searchAccount: "البحث في الحسابات",
    debitAccount: "من مذكورين (مدين)",
    creditAccount: "إلى مذكورين (دائن)",
    description: "شرح القيد",
    amount: "المبلغ",
    post: "ترحيل القيد",
    wellName: "اسم البئر",
    status: "الحالة",
    yield: "الإنتاج اليومي (BBL)",
    addWell: "إضافة بئر جديد +",
    addPartner: "إضافة شريك جديد +",
    actions: "الإجراءات",
    production: "إنتاج",
    exploration: "استكشاف",
    maintenance: "صيانة",
    closed: "مغلق/منتهي",
    petroleumSystem: "نظام محاسبة الطاقة المتخصص",
    hassan: "FinEx",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    history: "القيود المسجلة",
    date: "التاريخ",
    memo: "ملاحظة / بيان",
    balanced: "متوازن",
    unbalanced: "غير متوازن",
    difference: "الفرق",
    addLine: "إضافة سطر +",
    update: "تحديث",
    code: "الكود",
    account: "الحساب",
    synced: "متزامن",
    syncing: "جاري المزامنة...",
    auditLog: "سجل التعديلات والحذف",
    reasonRequired: "سبب الإجراء مطلوب",
    enterReason: "اكتب سبب التعديل أو الحذف هنا...",
    confirm: "تأكيد العملية",
    beforeEdit: "قبل التعديل",
    afterEdit: "بعد التعديل",
    deletedEntry: "قيد محذوف",
    timestamp: "وقت العملية",
    activeAccounts: "الحسابات النشطة",
    totalActiveAccounts: "إجمالي الحسابات النشطة",
    category: "التصنيف الرئيسي",
    allCategories: "كافة التصنيفات",
    grouping: "تصفية حسب المجموعة",
    partnerName: "اسم الشريك",
    sharePercent: "الحصة %",
    creditLimit: "الحد الائتماني",
    surveillanceFeed: "SURVEILLANCE FEED",
    save: "حفظ التغييرات",
    notification: "تنبيه النظام",
    partnerAdded: "تم إضافة شريك جديد بنجاح",
    partnerDeleted: "تم حذف الشريك وتعديل الأرصدة المالية",
    partnerUpdated: "تم تحديث بيانات الشريك وتسجيل التغيير",
    addWellBtn: "إضافة البئر",
    partnerAllocation: "توزيع حصص الشركاء",
    selectPartner: "اختر الشريك",
    shareInWell: "نسبة المشاركة في البئر (%)",
    totalShareExceeded: "إجمالي الحصص لا يمكن أن يتجاوز 100%",
    wellAdded: "تم إضافة البئر الجديد مع توزيع الحصص بنجاح",
    wellDeleted: "تم حذف البئر وتسجيل العملية في سجل التدقيق",
    wellUpdated: "تم تحديث بيانات البئر وحصص الشركاء",
    invalidPhone: "يرجى إدخل رقم هاتف بصيغة دولية صحيحة",
    invalidEmail: "يرجى إدخال بريد إلكتروني حقيقي",
    investmentData: "بيانات الاستثمار",
    totalRevenue: "إجمالي الإيرادات المحققة",
    wellsContributed: "الآبار المساهم فيها",
    investmentDistribution: "توزيع الاستثمارات",
    partnerIntel: "ذكاء الشريك",
    materialName: "اسم المادة",
    quantity: "الكمية",
    unitPrice: "سعر المفرد",
    totalPrice: "السعر الإجمالي",
    addMaterial: "إضافة مادة جديدة +",
    aiGenerateEntry: "توليد القيد بواسطة Gemini AI",
    stockReport: "معلومات المخزن",
    totalStockValue: "قيمة المخزون الكلية",
    inventoryReport: "تقرير الجرد اللحظي",
    accountingLock: "يجب تسجيل قيد محاسبي لإتمام الإضافة",
    materialAdded: "تمت إضافة المادة للمخزن بنجاح",
    aiGenerating: "جاري توليد القيد بواسطة AI...",
    unit: "الوحدة",
    entryDate: "التاريخ",
    issueToWell: "صرف لبئر",
    selectWell: "اختر البئر",
    issueAmount: "الكمية المصروفة",
    insufficientQuantity: "الكمية المطلوبة غير متوفرة في المخزن",
    materialIssued: "تم صرف المادة للبئر بنجاح",
    materialDeletedAuto: "تم حذف المادة تلقائياً لنفاذ الكمية",
    movementLog: "سجل الحركة",
    beforeQty: "قبل",
    afterQty: "بعد",
    changeQty: "التغيير",
    addStock: "زيادة كمية",
    newStockAdded: "تمت إضافة كمية جديدة للمادة",
    movementHistory: "تاريخ حركة المخزون",
    valueLost: "القيمة المحذوفة",
    quantityRemoved: "الكمية المحذوفة",
    actionReason: "سبب الإجراء",
    preview: "عرض التفاصيل",
    download: "تحليل PDF/Excel",
    aiAnalysis: "التحليل الذكي (AI Precision)",
    generateAiAnalysis: "توليد تحليل ذكي دقيق",
    downloadAiReport: "تحميل تقرير AI",
    financialReport: "التقرير المالي",
    inventoryReportFull: "تقرير المخزون الكامل",
    operationalReport: "التقرير التشغيلي (الآبار)",
    partnersReport: "تقرير الشركاء والاستثمارات",
    precisionReportTitle: "تقرير الرقابة الدقيقة",
    aiReportPlaceholder: "انقر لتوليد التحليل الذكي للبيانات الحالية...",
    addAccount: "إضافة حساب جديد",
    accountCodeExists: "عذراً، رقم الحساب هذا موجود مسبقاً!",
    balanceAtDeletion: "الرصيد وقت الحذف",
    accountAdded: "تمت إضافة الحساب الجديد بنجاح",
    accountDeleted: "تم حذف الحساب وتوثيق العملية في سجل التدقيق",
    balance: "الرصيد المالي",
    appearance: "المظهر العام",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الليلي",
    currencyFormat: "تنسيق العملة",
    mainCurrency: "العملة الأساسية",
    usd: "دولار أمريكي ($)",
    iqd: "دينار عراقي (IQD)",
    language: "اللغة",
    backupTitle: "إدارة النسخ الاحتياطي (Offline)",
    exportData: "تصدير البيانات (JSON)",
    importData: "استيراد البيانات",
    systemInfo: "معلومات النظام",
    version: "الإصدار",
    storageStatus: "حالة التخزين المحلي",
    importSuccess: "تم استيراد البيانات بنجاح، سيتم إعادة تحميل النظام.",
    importError: "عذراً، الملف غير صالح أو تالف.",
    masterKeyLabel: "مفتاح النظام (Master Key)",
    accessDenied: "عذراً، لا تملك صلاحية الوصول لهذا القسم",
    loginViaFile: "تسجيل دخول عبر ملف (.fnx)",
    exportUserFile: "تصدير ملف الدخول الآمن",
    invalidFile: "الملف المرفوع غير صالح أو غير متوافق",
    userNotFound: "عذراً، لم يتم العثور على هذا المستخدم في قاعدة بيانات النظام",
    expiredAccess: "انتهت صلاحية الدخول، يرجى مراجعة مدير النظام",
    deviceMismatch: "عذراً، هذا الملف مخصص لجهاز آخر فقط",
    killSwitchAlert: "تم تفعيل قفل النظام للأمان، تم مسح بيانات الجلسة",
    exportKillSwitch: "تصدير ملف قفل الحساب (Kill-Switch)",
    exportActivationKey: "تصدير مفتاح التنشيط",
    unlockedSuccess: "تم تفعيل حسابك بنجاح بواسطة المدير. يمكنك الدخول الآن.",
    installApp: "تثبيت تطبيق FineX",
    pwaSupport: "التطبيق يعمل الآن كبرنامج مستقل (Offline)"
  },
  en: {
    dashboard: "Dashboard",
    journal: "General Ledger",
    wells: "Wells Management",
    partners: "Partners Management",
    inventory: "Inventory Management",
    reports: "Reports & Oversight Center",
    chart: "Chart of Accounts",
    audit: "Audit Log & History",
    users: "User Management",
    settings: "Settings",
    logout: "Logout",
    loginTitle: "FineX Energy System",
    loginSub: "Please enter your credentials to access the system",
    adminSetupTitle: "System Admin Setup",
    adminSetupSub: "Please enter the first administrator data to initialize the system",
    adminLogin: "Admin Login",
    phone: "Phone Number",
    password: "Password",
    loginBtn: "Login to System",
    setupBtn: "Setup Account & Continue",
    invalidLogin: "Invalid phone number or password",
    userBlocked: "Sorry, your access has been blocked by administration",
    fullName: "Full Name",
    jobTitle: "Job Title",
    addUser: "Add New User +",
    permissions: "Access Permissions",
    block: "Block",
    unblock: "Unblock",
    active: "Active",
    blocked: "Blocked",
    performedBy: "Performed By",
    systemAlert: "System Alert",
    totalAssets: "Total Assets",
    totalLiabilities: "Total Liabilities",
    actualProduction: "Actual Production",
    wtiPrice: "WTI Crude Price",
    realTime: "REAL-TIME",
    newEntry: "Add New Entry",
    searchAccount: "Search Accounts",
    debitAccount: "Debits (From)",
    creditAccount: "Credits (To)",
    description: "Description",
    amount: "Amount",
    post: "Post Entry",
    wellName: "Well Name",
    status: "Status",
    yield: "Daily Yield (BBL)",
    addWell: "Add New Well +",
    addPartner: "Add New Partner +",
    actions: "Actions",
    production: "Production",
    exploration: "Exploration",
    maintenance: "Maintenance",
    closed: "Closed/Plugged",
    petroleumSystem: "Specialized Energy Accounting System",
    hassan: "FinEx",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    history: "Registered Entries",
    date: "Date",
    memo: "Memo / Note",
    balanced: "Balanced",
    unbalanced: "Unbalanced",
    difference: "Difference",
    addLine: "Add Line +",
    update: "Update",
    code: "Code",
    account: "Account",
    synced: "Synced",
    syncing: "Syncing...",
    auditLog: "Audit Log & History",
    reasonRequired: "Action Reason Required",
    enterReason: "Enter the reason for modification or deletion...",
    confirm: "Confirm Action",
    beforeEdit: "Before Modification",
    afterEdit: "After Modification",
    deletedEntry: "Deleted Entry",
    timestamp: "Timestamp",
    activeAccounts: "Active Accounts",
    totalActiveAccounts: "Total Active Accounts",
    category: "Main Category",
    allCategories: "All Categories",
    grouping: "Filter by Group",
    partnerName: "Partner Name",
    sharePercent: "Share %",
    creditLimit: "Credit Limit",
    surveillanceFeed: "SURVEILLANCE FEED",
    save: "Save Changes",
    notification: "System Alert",
    partnerAdded: "Partner successfully added",
    partnerDeleted: "Partner deleted and financial balances adjusted",
    partnerUpdated: "Partner data updated and changes logged",
    addWellBtn: "Add Well",
    partnerAllocation: "Partner Allocation",
    selectPartner: "Select Partner",
    shareInWell: "Well Participation Share (%)",
    totalShareExceeded: "Total shares cannot exceed 100%",
    wellAdded: "New well added with partner allocations",
    wellDeleted: "Well deleted and logged in audit history",
    wellUpdated: "Well data and partner allocations updated",
    invalidPhone: "Please enter a valid international phone number",
    invalidEmail: "Please enter a valid email address",
    investmentData: "Investment Data",
    totalRevenue: "Total Realized Revenue",
    wellsContributed: "Contributed Wells",
    investmentDistribution: "Investment Distribution",
    partnerIntel: "Partner Intelligence",
    materialName: "Material Name",
    quantity: "Quantity",
    unitPrice: "Unit Price",
    totalPrice: "Total Price",
    addMaterial: "Add New Material +",
    aiGenerateEntry: "AI Journal Entry (Gemini)",
    stockReport: "Stock Report",
    totalStockValue: "Total Stock Value",
    inventoryReport: "Real-time Inventory Report",
    accountingLock: "Accounting entry required to complete addition",
    materialAdded: "Material added to stock successfully",
    aiGenerating: "Generating entry with AI...",
    unit: "Unit",
    entryDate: "Date",
    issueToWell: "Issue to Well",
    selectWell: "Select Well",
    issueAmount: "Issue Quantity",
    insufficientQuantity: "Requested quantity is not available in stock",
    materialIssued: "Material successfully issued to well",
    materialDeletedAuto: "Material automatically deleted due to zero quantity",
    movementLog: "Movement Log",
    beforeQty: "Before",
    afterQty: "After",
    changeQty: "Change",
    addStock: "Increase Quantity",
    newStockAdded: "New stock quantity added to material",
    movementHistory: "Stock Movement History",
    valueLost: "Value Deleted",
    quantityRemoved: "Quantity Deleted",
    actionReason: "Action Reason",
    preview: "Preview Details",
    download: "Export PDF/Excel",
    aiAnalysis: "AI Analysis (Precision)",
    generateAiAnalysis: "Generate Precision AI Analysis",
    downloadAiReport: "Download AI Report",
    financialReport: "Financial Health Report",
    inventoryReportFull: "Full Inventory Status",
    operationalReport: "Operational (Wells) Report",
    partnersReport: "Partners & Investment Report",
    precisionReportTitle: "Precision Oversight Report",
    aiReportPlaceholder: "Click to generate smart analysis for current data...",
    addAccount: "Add New Account",
    accountCodeExists: "Error: Account code already exists!",
    balanceAtDeletion: "Balance at deletion",
    accountAdded: "Account successfully added",
    accountDeleted: "Account deleted and logged in audit log",
    balance: "Balance",
    appearance: "Appearance",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    currencyFormat: "Currency Format",
    mainCurrency: "Main Currency",
    usd: "US Dollar ($)",
    iqd: "Iraqi Dinar (IQD)",
    language: "Language",
    backupTitle: "Backup Management (Offline)",
    exportData: "Export Data (JSON)",
    importData: "Import Data",
    systemInfo: "System Information",
    version: "Version",
    storageStatus: "Storage Status",
    importSuccess: "Data imported successfully. System will reload.",
    importError: "Error: Invalid or corrupted backup file.",
    masterKeyLabel: "Master Key",
    accessDenied: "Sorry, you do not have permission to access this section",
    loginViaFile: "Login via File (.fnx)",
    exportUserFile: "Export Secure Login File",
    invalidFile: "Invalid or incompatible file",
    userNotFound: "Error: User not found in system database",
    expiredAccess: "Access Expired, please contact system admin",
    deviceMismatch: "Device Mismatch. This file is bound to another device",
    killSwitchAlert: "Kill-Switch activated for security. Session wiped.",
    exportKillSwitch: "Export Account Kill-Switch",
    exportActivationKey: "Export Activation Key",
    unlockedSuccess: "Your account has been successfully activated by the manager. You can log in now.",
    installApp: "Install FineX App",
    pwaSupport: "The app now works as a standalone program (Offline)"
  }
};

export const WELL_STATUS_MAP = {
  [WellStatus.PRODUCTION]: { ar: 'إنتاج', en: 'Production', color: 'text-green-500' },
  [WellStatus.EXPLORATION]: { ar: 'استكشاف', en: 'Exploration', color: 'text-blue-500' },
  [WellStatus.MAINTENANCE]: { ar: 'صيانة', en: 'Maintenance', color: 'text-yellow-500' },
  [WellStatus.CLOSED]: { ar: 'مغلق/منتهي', en: 'Closed/Plugged', color: 'text-red-500' },
};
